version: '2'
services:
  dotnet:
    build: .
    restart: "no"
    ports:
     - "5000:5000"
    environment:
      SQLSERVER_HOST: sqlserver
    links:
      - sqlserver
  sqlserver:
    image: microsoft/mssql-server-linux
    restart: "no"
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Testing123"
